apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJSR1Z1YVhNMk15MXpPbWRvY0Y4eGNFOUpRMDFOVWpGcFRVNHpjSFF6Y1hOQmRsbHBlRFpHUTBkb1VYRXpVVXc1VVZRPSIKCQl9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
